### ISSUE TITLE
Running the git commit command in the Forks... Assignment

### ISSUE THREAD

**Issue by jkoosak1** [ccarrollATjhuecon/Methods#10]
In the Fork-Methods-Repo--Add-Moniker--Make-Pull-Request Assignment, when I tried runing the git commit command, I got an error saying "fatal: unable to auto-detect email address". Maybe it would be useful to add a line telling us to run the git config commands first ie "git config-- global user.email [email]" and "git config-- global user.name [name]".

**Comment by iworld1991** [comment]
It was fixed by the pull request by Julien #1

**Comment by llorracc** [comment]
This was fixed by the pull request from [AcalinJ](https://github.com/ccarrollATjhuecon/Methods/pull/4)
