### ISSUE TITLE
Permission denied error after 'chmod' command

### ISSUE THREAD

**Issue by melihfirat** [ccarrollATjhuecon/Methods#12]
While trying to execute my bash script, I used 'chmod a+x *.sh' command to make it executable and I had the "permission denied " error. Then I used 'chmod u+x program_name' and it worked. After 'chmod' command, _u_ stands for _user_ and _a_ stands for _all_.

**Comment by llorracc** [comment]
Need to do this as the superuser: "sudo"

This is because, to change permissions for users other than yourself ("a+x") you need to be superuser
