### ISSUE TITLE
Software Carpentries Hyperlink on Assignment 00_Start-Learning-Git

### ISSUE THREAD

**Issue by raytobing** [ccarrollATjhuecon/Methods#26]
On the instructions for assignment 00, rather than linking to the instructor's notes, the Software Carpentry hyperlink should instead lead directly to the following:
https://swcarpentry.github.io/git-novice/

The original hyperlink also contains a number of steps that can be followed and can easily be mistaken as the "sections 1-9 of the Software Carpentries introduction to Git" that is stated on the assignment instruction.

**Comment by ccarrollATjhuecon** [comment]
Will be fixed when https://github.com/ccarrollATjhuecon/Methods/pull/34 is merged in.
