### ISSUE TITLE
How-To-Turn-In-Assignments file

### ISSUE THREAD

**Issue by wko5** [ccarrollATjhuecon/Methods#28]
~ccarrollATjhuecon/Methods/Assignments/02-30_Report-Your-Results-Using-Markdown

Our third assignment which has a directory as above said that 

"For each assignment (starting with this one), follow the instructions in How-To-Turn-In-Assignments to create a copy of the assignment with the appropriate name"

But I cannot find 'How-To-Turn-In-Assignments' in this GitHub repository.

**Comment by ccarrollATjhuecon** [comment]
Sorry, I have now edited the "report-your-results" assignment so that it no longer makes reference to the out of date "How-To-Turn-In-Assignments" instructions
