### ISSUE TITLE
Empty folders 

### ISSUE THREAD

**Issue by HTS420** [ccarrollATjhuecon/Methods#29]
Under the directory Methods/Syllabus/, there are no files in the folders Other-Resources and Topics, although it seems like with useful resources. Some folders inside Other-Resources are even nested with a lot of layers but is empty in the end directory. Maybe some descriptions can be added or simply removed them to simplify the searching process for relevant materials in the whole repository.

**Comment by ccarrollATjhuecon** [comment]
I will be populating folders that are now empty as the semester proceeds.
