### ISSUE TITLE
Write-Your-First-Bash-Script-Using-Emacs.md

### ISSUE THREAD

**Issue by HTS420** [ccarrollATjhuecon/Methods#30]
In this file we are instructed to create the file named as `Write-Your-First-Bash-Script-Using-Emacs_[Moniker].sh`
However later the file named `First-Bash-Script-[Moniker].sh` was called.
It seems that only one out of two different names should be used throughout the file to ensure the executability.

**Comment by ccarrollATjhuecon** [comment]
Fixed by https://github.com/ccarrollATjhuecon/Methods/issues/32
