### ISSUE TITLE
Syllabus & Assignment 00

### ISSUE THREAD

**Issue by nkodua** [ccarrollATjhuecon/Methods#31]
In Syllabus_Methods.md, the word "instructions" is highlighted but the link does not work perhaps because of security reasons. On a Mac, when we click on appointments, instead of taking to the link, Mac wants to download the calendar.
Additionally, in assignment 00, since we are told to look at the sections 1-9, I believe that the link should be https://swcarpentry.github.io/git-novice/ instead of what is given there.

**Comment by llorracc** [comment]
Have fixed the "Appointments" link.
