### ISSUE TITLE
Typo in Write-Your-First-Bash-Script-Using-Emacs.md

### ISSUE THREAD

**Issue by wdu9** [ccarrollATjhuecon/Methods#32]
The instructions of this assignment tell you to create a file named "Write-Your-First-Bash-Script-Using-Emacs_[Moniker].sh" however later on in the assignment you are instructed to execute a file of a different name: "./First-Bash-Script-[Moniker].out" leading to a message saying "file not found".

**Comment by ccarrollATjhuecon** [comment]
@wdu9 fixed this via a Pull Request
